matrix:
  include:
  - language: python
    python: 3.6
    cache: pip
    before_install:
    - cd src/python/
    - pip install -U pip
    install:
    - pip install -U tox-travis pipenv_to_requirements
    before_script:
    - pipenv_to_requirements -f
    script:
    - tox

  - language: python
    python: 3.7
    cache: pip
    before_install:
    - cd src/python/
    - pip install -U pip
    install:
    - pip install -U tox-travis codecov pipenv_to_requirements
    before_script:
    - pipenv_to_requirements -f
    script:
    - tox
    after_success:
    - codecov
